### ISSUE TITLE
GDOwnerNode does not exists (Godot 3.2.2 stable Mono version)

### ISSUE THREAD

**Issue by DadeKuma** [Ranoller/gddragonbones#11]
Hello, while generating the mono glue I get the following error: (using Godot 3.2.2 stable Mono version)

`ERROR: BindingsGenerator::_generate_cs_type: Base type 'GDOwnerNode' does not exist, for class 'GDDragonBones'.
   At: modules\mono\editor\bindings_generator.cpp:1210
ERROR: BindingsGenerator::generate_cs_api: Generation of the Core API C# project failed.
   At: modules\mono\editor\bindings_generator.cpp:1115
ERROR: BindingsGenerator::handle_cmdline_args: --generate-mono-glue: Failed to generate the C# API.
   At: modules\mono\editor\bindings_generator.cpp:3181
`

Am I doing something wrong? Does this module support mono? Thanks!

**Comment by Ranoller** [comment]
No mono support, sorry.
